version: "3"
services:
    iscram:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
          - ./lora:/root/ns-allinone-3.31/ns-3.31/src/lora/
          - ./experiments:/root/ns-allinone-3.35/ns-3.35/scratch/iscram_d2d/
