version: "3"
services:
    lora_d2d:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
          - ./results:/results
          - ./lorawan:/root/ns-allinone-3.35/ns-3.35/src/lorawan/
          - ./experiments:/root/ns-allinone-3.35/ns-3.35/scratch/lora_d2d/
          - ./experiments:/root/ns-allinone-3.35/ns-3.35/experiments
        environment:
          - RUN
          - LOG_PATH
